# Generated by Django 4.2 on 2023-04-20 10:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0003_add_slug_to_product'),
    ]

    operations = [
        migrations.RunSQL(
        """
            INSERT INTO store_collection (title)
            VALUES ('collection 1')                  
        """, """
            DELETE FROM store_collection
            WHERE title='collection 1'                  
        """)
    ]
